id = "kagimcp"
name = "Kagi MCP Server"
description = "Model Context Protocol Server for Kagi Search"
version = "0.0.24"
schema_version = 1
authors = ["John Mylchreest <jmylchreest@users.noreply.github.com>"]
repository = "https://github.com/jmylchreest/kagimcp-zed"

[context_servers.kagimcp]
name = "Kagi MCP Server"
